name             'base'
depends          'selinux', '~> 0.9.0'
depends          'sudo', '~> 2.7.1'
depends          'system', '~> 0.6.3'
maintainer       'ikuwow'
maintainer_email 'degawa@ikuwow.com'
license          'All rights reserved'
description      'Installs/Configures base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.4'
